In [131]:
#Passo 1: Importa a base de dados
import pandas as pd

tabela = pd.read_csv("telecom_users.csv")

#Passo 2: Visualizar a base de dados
tabela = tabela.drop("Unnamed: 0", axis=1)
tabela = tabela.drop("IDCliente", axis=1)
display(tabela)
# - Entender quais as informações tão disponiveis 
# - Descobrir as cagadas da base de dados

,Genero,Aposentado,Casado,Dependentes,MesesComoCliente,ServicoTelefone,MultiplasLinhas,ServicoInternet,ServicoSegurancaOnline,ServicoBackupOnline,...,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,ValorMensal,TotalGasto,Churn,Codigo
0,Masculino,0,Sim,Sim,72,Sim,Sim,Nao,SemInternet,SemInternet,...,SemInternet,SemInternet,SemInternet,2 anos,Nao,CartaoCredito,24.10,1734.65,Nao,NaN
1,Feminino,0,Nao,Nao,44,Sim,Nao,Fibra,Nao,Sim,...,Nao,Sim,Nao,Mensal,Sim,CartaoCredito,88.15,3973.2,Nao,NaN
2,Feminino,1,Sim,Nao,38,Sim,Sim,Fibra,Nao,Nao,...,Nao,Nao,Nao,Mensal,Sim,DebitoAutomatico,74.95,2869.85,Sim,NaN
3,Masculino,0,Nao,Nao,4,Sim,Nao,DSL,Nao,Nao,...,Nao,Nao,Sim,Mensal,Sim,BoletoEletronico,55.90,238.5,Nao,NaN
4,Masculino,0,Nao,Nao,2,Sim,Nao,DSL,Sim,Nao,...,Nao,Nao,Nao,Mensal,Nao,BoletoEletronico,53.45,119.5,Nao,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,Masculino,0,Sim,Nao,1,Sim,Nao,Fibra,Sim,Nao,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,95.00,95,Sim,NaN
5982,Feminino,0,Sim,Sim,23,Sim,Sim,DSL,Sim,Sim,...,Sim,Sim,Sim,2 anos,Sim,CartaoCredito,91.10,2198.3,Nao,NaN
5983,Masculino,0,Sim,Sim,12,Sim,Nao,Nao,SemInternet,SemInternet,...,SemInternet,SemInternet,SemInternet,Mensal,Sim,BoletoEletronico,21.15,306.05,Nao,NaN
5984,Masculino,1,Nao,Nao,12,Sim,Sim,Fibra,Nao,Nao,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,99.45,1200.15,Sim,NaN
5985,Masculino,0,Nao,Nao,26,Sim,Nao,Nao,SemInternet,SemInternet,...,SemInternet,SemInternet,SemInternet,Anual,Nao,CartaoCredito,19.80,457.3,Nao,NaN

In [129]:
#Passo 3: Tratamento de dados
# - Valores que estão sendo reconhecidos de forma errada
tabela["TotalGasto"] = pd.to_numeric(tabela["TotalGasto"], errors="coerce")

# - Valores vazios
#Deletando as colunas vazias
# axis = 0 _> linha axis = 1 _> coluna
tabela = tabela.dropna(how="all", axis=1)
#Deletando as linhas vazias

print(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Genero                  5986 non-null   object
 1   Aposentado              5986 non-null   int64
 2   Casado                  5986 non-null   object
 3   Dependentes             5985 non-null   object
 4   MesesComoCliente        5986 non-null   int64
 5   ServicoTelefone         5986 non-null   object
 6   MultiplasLinhas         5986 non-null   object
 7   ServicoInternet         5986 non-null   object
 8   ServicoSegurancaOnline  5986 non-null   object
 9   ServicoBackupOnline     5986 non-null   object
 10  ProtecaoEquipamento     5986 non-null   object
 11  ServicoSuporteTecnico   5986 non-null   object
 12  ServicoStreamingTV      5986 non-null   object
 13  ServicoFilmes           5986 non-null   object
 14  TipoContrato            5986 non-null   object
 15  FaturaDigital           5986 non-null   object
 16  FormaPagamento          5986 non-null   object
 17  ValorMensal             5986 non-null   float64
 18  TotalGasto              5976 non-null   float64
 19  Churn                   5985 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 935.4+ KB
None

In [136]:
#Passo 4: Análise inicial
# Como estão os nossos cancelamentos?
print(tabela["Churn"].value_counts())
print(tabela["Churn"].value_counts(normalize=True).map("{:.1%}".format))

Nao    4398
Sim    1587
Name: Churn, dtype: int64
Nao    73.5%
Sim    26.5%
Name: Churn, dtype: object

In [134]:
#Passo 5: Análise mais completa
#Comparar cada coluna da minha tabela com  a coluna de cancelamento
import plotly.express as px

#Etapa 1: criar o gráfico 
for coluna in tabela.columns:
    grafico = px.histogram(tabela, x=coluna, color="Churn")
    #Etapa 2: exibir o grafico
    grafico.show()

KeyError: (nan, '', '', '', '')